//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> amout { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
